### PR TITLE
more makefile enhancements

### PR DESCRIPTION
**Pull request by Un1q32**

### CODE REVIEW

**Comment by Arkaeriit** [comment]
There is some stuff I really like in that PR. The renaming of `TARGET_DIR_BIN` into `DESTDIR`, the addition of the native optimizations, and the removal of the legacy build script are all great.

But there is other things I am not very sure about. What does using `install` instead of `cp` brings to the table? Furthermore, I don't really like the use of `ln` to link `ex` to `vi`. It looks like you are linking the local executable to the destination directory, which is not a very sane way to do it. But even if you were linking `$(DESTDIR)/vi` to `$(DESTDIR)/ex`, some people might want to delete `vi` and only keep `ex`, which would not work.

**Comment by Arkaeriit** [comment]
I am still very grateful for all the nice work you are doing on this repo.

**Comment by Un1q32** [comment]
alright I've setup ln to do a hard link instead of a symlink, so we still save space while allowing people to move around and delete binaries without breaking it.  As for why I choose to use `install` instead of `cp`, it's just so we can strip the binary without running strip separately, however I realize this might cause issues for cross compiling, so I'll add a separate strip step

**Comment by Arkaeriit** [comment]
This looks and works great. Thank you for your work.

**Pull request merged**
